### ISSUE TITLE
Bower component

### ISSUE THREAD

**Issue by sindresorhus** [jlong/sass-bootstrap-defunct#38]
Would be very useful if sass-twitter-bootstrap was available through the front-end package manager Bower: https://github.com/twitter/bower

That way you could just do `bower install sass-twitter-bootstrap` and have it included in your app.

I can submit a PR for the required component.json if you're interested.

**Comment by jlong** [comment]
How is this different from the existing components.json?

**Comment by sindresorhus** [comment]
Nothing, didn't notice you already had it.

**Comment by m5o** [comment]
Sorry for jiggling this Issue, I played with the new github iPhone App for Issues. 
Should we close this one?

**Comment by sindresorhus** [comment]
@jlong Actually, when looking at it, the component.json has the name `bootstrap`, while this is also the name of the component for the official Bootstrap component.

Can you change it to `sass-bootstrap` or something and register it on Bower?

https://github.com/twitter/bower#authoring-packages

**Comment by jlong** [comment]
@sindresorhus I probably won't have time to look at this any time soon, but I've added you as a contributor on this project. Would you mind pulling together a fix on your own and registering it with Bower?

Since this will be your first commit, could you also put it in a pull-request for the rest of us to review?

Thanks!

**Comment by sindresorhus** [comment]
Sure, submitted a PR.

Btw, we're using this in [yeoman](http://yeoman.io).
