### ISSUE TITLE
README is hard to understand

### ISSUE THREAD

**Issue by tvw** [jlong/sass-bootstrap-defunct#49]
I do not understand it at all.

I came here to use the sass version of twitter bootstrap, but the quick start tells me to use the original less version from twitter. I think the README needs to be improved. So why did I came here?

**Comment by alanjds** [comment]
I Agree. If you follow the README instructions you get the original Twitter's Bootstrap. Is worth to at least change the install instructions.

**Comment by m5o** [comment]
In general you have to know that all the instuctions are a 1:1 copy from the upstream (twitter/bootstrap). If you read further there are SASS sections. They should make it clear. please read the docs from start to end

**Comment by tvw** [comment]
I read even the SASS-sections, but I thought, they apply only to contributors of this project and not to the users.

**Comment by GaryJones** [comment]
How about a bold note at the start of the readme that says that this is the Sass version of the project, what follows is the original readme, with a section for Sass at the end?

**Comment by tvw** [comment]
I think, it is not clear at all, what the purpose of this project is? I thought, I can use it to integrate Twitter-Bootstrap into my application in a SASS-style. But when the original README is so important, it seems as if the purpose of this project is to contribute to Twitter-Bootstrap by using SASS instead of LESS. I did not expect that, since then somebody has always to translate all changes back to LESS.

So when I can only integrate the final CSS into my project, what does it help me, when it is compiled from SASS instead from LESS. I expect both to give me the same resulting CSS. I think, it is not clear, what is the preferred way how to get to a customized CSS for a project without touching the original scss-sources.

**Comment by jan-harmsen** [comment]
well, the purpose of the project is to provide a sass-version of twitter bootstrap. How you get the resulting css is completely up to your project's requirements / infrastructure. If you look at the lib folder you will see that it contains all the .scss files for twitter bootstrap, you combine those with your project's sass / .scss files and that's it, what else do you need?

**Comment by tvw** [comment]
What I need? A README, that matches the project itself. When I read "Quickstart" I expect it to tell me how to quickstart with the project and not the original twitter bootstrap. I was there before and was instead searching for a different (and sassy) approach to use it. What I expect from a projects README is,  that it tells me what the project is about, why it exists and what the developers expect, how one make use of it.

At the end, you are right, all what you need is in the lib-folder. But before you find out, that this is all you get, the README, which you read first, confuses you a lot. No README at all would have been much better. Even for bug reports you are sent to the twitter-project and you have to watch carefully, what happens, when you follow the link offered in the README, since both issue trackers are on github and look the very same on first sight. I guess most people would expect it to refer to the projects bug-tracker, like I did. I noticed after reading a few issues, that I was wrong, but why do I have to worry about things like this?

But since most other projects explain their projects in their README, it is absolutely confusing, that the README refers to a completely other project. This breaks all expectations you have by learning and visiting other github-projects. So I suggest writing your own README and refer to the twitter-README. That is what hyperlinks are very good for.

**Comment by GaryJones** [comment]
@tvw I think you're approaching this project in the wrong way - it's not a standalone project, for which a more project-specific comprehensive readme would indeed be expected, but effectively an extension of Bootstrap. 

If you understand what the Bootstrap project is about, then you'll know that this is simply a port that uses SASS instead of LESS. As a developer, it should be clear where a problem is likely to be, and hence where to report the issue. Line-height on blockquotes not right? Go check Bootstrap and file an issue there. Typo in .scss that stops it compiling? Report it here.

Other than a one-line explanation at the start of the readme, which can refer to the end of the readme (or arguably deleting all of the Bootstrap readme content and just paste a link to the Bootstrap project), there's not too much that should be added here - it's a live port of another project, so the expectation is to match the same end result as the original project. Nothing added, nothing removed.
