### ISSUE TITLE
Endless recursion errors 

### ISSUE THREAD

**Issue by ghost** [jlong/sass-bootstrap-defunct#99]
I seem to be getting endless recursion errors when compiling with https://github.com/richthegeek/phpsass  

the compiler fails at _grid.scss container-fixed mixin.

Is this a sass-bootstrap issue?

**Comment by FelixSchwarz** [comment]
Speaking as someone with no prior experience with sass-bootstrap: I'm pretty sure that this is a phpsass issue. If sass-bootstrap compiles with Ruby sass (and it does) then the problem is in your compiler. So I think you should file a ticket with phpsass (edit: I noticed that you already did this already actually: richthegeek/phpsass#127).

**Comment by ghost** [comment]
I think so too. I found a workaround to get it running but it was pretty hacky and not as graceful - not worth the pull request.
